name: Pages Doctor (Vite + React)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pages-doctor:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      EXPECTED_BASE: "/${{ github.event.repository.name }}/"
      OWNER: ${{ github.repository_owner }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Quick config checks (Vite base, Router basename)
        shell: bash
        run: |
          echo "### Pages Doctor — config checks" >> $GITHUB_STEP_SUMMARY
          echo "- Expected Vite base: \`${EXPECTED_BASE}\`" >> $GITHUB_STEP_SUMMARY

          # 1) Vite base must match /<repo>/
          if grep -R --line-number -E "base:\s*['\"]${EXPECTED_BASE}['\"]" vite.config.* >/dev/null 2>&1; then
            echo "✅ Vite base OK" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Vite base not found or mismatched. Add in vite.config.js: \`base: \"${EXPECTED_BASE}\",\`" >> $GITHUB_STEP_SUMMARY
            echo "::warning title=Vite base mismatch::Set base: \"${EXPECTED_BASE}\" in vite.config.js"
          fi

          # 2) Router should use basename = import.meta.env.BASE_URL
          if grep -R -E "BrowserRouter.*basename=.*import\.meta\.env\.BASE_URL" -n src >/dev/null 2>&1; then
            echo "✅ Router basename OK" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Router basename not detected. Use: <BrowserRouter basename={import.meta.env.BASE_URL}>." >> $GITHUB_STEP_SUMMARY
            echo "::warning title=Router basename missing::Use import.meta.env.BASE_URL"
          fi

      - name: Build 🔧
        run: npm run build

      - name: Verify dist/index.html (no /src/main.jsx, has hashed assets)
        shell: bash
        run: |
          echo "### Build checks" >> $GITHUB_STEP_SUMMARY
          test -f dist/index.html || (echo "❌ dist/index.html missing (build failed?)" >> $GITHUB_STEP_SUMMARY; exit 1)

          if grep -q "/src/main.jsx" dist/index.html; then
            echo "❌ Found dev script tag (/src/main.jsx) in dist/index.html — you're publishing DEV HTML." >> $GITHUB_STEP_SUMMARY
            echo "::error title=DEV index.html detected::dist/index.html references /src/main.jsx"
            exit 1
          else
            echo "✅ No /src/main.jsx in dist" >> $GITHUB_STEP_SUMMARY
          fi

          if grep -E -q "assets/.+\.js" dist/index.html; then
            echo "✅ Has compiled asset references (assets/*.js)" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ No assets/*.js references in dist/index.html — build likely broken." >> $GITHUB_STEP_SUMMARY
            echo "::error title=No compiled assets in dist/index.html::Expected assets/*.js"
            exit 1
          fi

      - name: Upload dist artifact 📦
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist
          if-no-files-found: error
          retention-days: 5

      # Optional: live health check if GH Pages is already configured
      - name: Live health check (best-effort)
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          URL="https://${OWNER}.github.io/${REPO_NAME}/"
          echo "### Live check (best-effort)" >> $GITHUB_STEP_SUMMARY
          echo "- Checking ${URL}" >> $GITHUB_STEP_SUMMARY

          # Retry for up to ~60s because Pages can take time to refresh
          ok=0
          for i in {1..10}; do
            code=$(curl -s -o /tmp/p.html -w "%{http_code}" "${URL}" || true)
            if [ "$code" = "200" ] || [ "$code" = "301" ] || [ "$code" = "302" ]; then
              if grep -E "assets/.+\.js" /tmp/p.html >/dev/null 2>&1; then
                echo "✅ Live page responds (${code}) and includes assets/*.js" >> $GITHUB_STEP_SUMMARY
                ok=1
                break
              fi
            fi
            sleep 6
          done
          if [ "$ok" = "0" ]; then
            echo "⚠️ Live page not ready or misconfigured. Common causes:" >> $GITHUB_STEP_SUMMARY
            echo "- Pages source not set to \`gh-pages / root\`" >> $GITHUB_STEP_SUMMARY
            echo "- Workflow not deploying **dist/** (folder mismatch)" >> $GITHUB_STEP_SUMMARY
            echo "- Wrong \`base\` in vite.config.js (should be \`${EXPECTED_BASE}\`)" >> $GITHUB_STEP_SUMMARY
            echo "- Router missing \`basename={import.meta.env.BASE_URL}\`" >> $GITHUB_STEP_SUMMARY
          fi
